# Generated by Django 3.2.4 on 2021-08-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daihugo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
